os: linux
sudo: false   # Uses sudo for e.g. binding the port but not for testing
language: python
python:
  - 3.5
cache: pip
install: 
  - pip install .
  - pip install -r requirements-dev.txt
before_script:
  - mypy tensorhive tests
  - python -m flake8 tensorhive tests
script:
  - pytest
